# SPDX-License-Identifier: MPL-2.0
# Fail-closed REUSE compliance gate.
# Blocks merge if any file is missing SPDX copyright/licence information.
---
name: REUSE compliance

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install reuse
        run: pip install reuse

      - name: Check REUSE compliance
        run: reuse lint
